# docker-compose -f docker-compose.yaml up -d
services:
  otel-collector:
    container_name: otelcol-contrib
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./docker_otel-config_r-shiny.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    env_file:
      - .env # Be sure to change API key here
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      TZ: 'America/Toronto'
    restart: unless-stopped

  fibonacci:
    container_name: shiny
    image: r-shiny:latest
    volumes:
      - ./shiny.R:/opt/r/shinyr.R
    ports:
      - "8000:8000"
    environment:
      TZ: 'America/Toronto'
    restart: unless-stopped