# Image must be built to add "openmetrics" package
# docker build . -t r-shiny:latest
FROM rocker/shiny:latest

EXPOSE 8000

RUN R -e "install.packages('openmetrics', dependencies=TRUE, repos='http://cran.rstudio.com/')"

WORKDIR /opt/r

COPY shiny.R shiny.R

ENTRYPOINT ["Rscript", "shiny.R"]

# Run otelcol-contrib to send metrics. Windows uses ${pwd} everyone else uses $(pwd)
# docker run -d --env-file .env -v ${pwd}/docker_otel-config_r-shiny.yaml:/etc/otelcol-contrib/config.yaml otel/opentelemetry-collector-contrib:latest
