extensions:
  health_check:

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'r-batch-job'
          scrape_interval: 5s
          static_configs:
            - targets: ['host.docker.internal:9091']
          metric_relabel_configs:
          - source_labels: [__name__]
            regex: "(go_.*|process_.*|pushgateway_.*)"
            action: drop

processors:
  metricstransform/batch:
    transforms:
      include: batch_duration_seconds
      action: update
      new_name: http.server.duration
      operations:
        - action: experimental_scale_value
          experimental_scale: 1000
        - action: update_label
          label: path
          new_label: http.target

  attributes/batch:
    actions:
      - key: service.instance.id
        action: insert
        value: localhost
      - key: tags.team
        action: insert
        value: datacrunch

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [metricstransform/batch, attributes/batch]
      exporters: [otlp]