# docker-compose -f docker-compose.yaml up -d
services:
  otel-collector:
    container_name: otelcol-contrib
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./docker_otel-config_r-batch.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    env_file:
      - .env # Be sure to change API key here
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      TZ: 'America/Toronto'
    restart: unless-stopped

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    environment:
      TZ: 'America/Toronto'
    restart: unless-stopped

  batchjob:
    container_name: batch
    image: r-batch:latest
    volumes:
      - ./batchjob.R:/opt/r/batchjob.R
      - ./jobs/*:/opt/r/jobs/*
    ports:
      - "8000:8000"
    environment:
      TZ: 'America/Toronto'
    restart: unless-stopped